version: 2.1

jobs:
  lint_and_test:
    docker:
      - image: circleci/openjdk:17-jdk
    steps:
      - checkout

      - run:
          name: Lint
          command: |
            mvn checkstyle:checkstyle

      - run:
          name: Test
          command: |
            mvn clean test

workflows:
  backend:
    jobs:
      - lint_and_test
