version: 2.1

jobs:
  lint_and_test:
    docker:
      - image: cimg/openjdk:17.0.8
    steps:
      - checkout

      - run:
          name: Lint
          command: |
            cd backend
            mvn checkstyle:checkstyle

      - run:
          name: Test
          command: |
            cd backend
            mvn clean test

workflows:
  backend:
    jobs:
      - lint_and_test
