-- CREATE TABLE DECK (
--     ID        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--     PLAYER_ID UUID NOT NULL,
--     CARD_1_ID UUID NOT NULL,
--     CARD_2_ID UUID NOT NULL,
--     CARD_3_ID UUID NOT NULL,
--     CARD_4_ID UUID NOT NULL,
--     FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER (ID)
-- );

CREATE TABLE ALGORE_MEASUREMENT (
    ID   UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    NAME VARCHAR2(100) NOT NULL,
);

CREATE TABLE ALGORE_INGRIDIENT (
    ID   UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    NAME VARCHAR2(100) NOT NULL,
);

CREATE TABLE ALGORE_SEASON (
    ID   UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    NAME VARCHAR2(100) NOT NULL,
    FROM DATE          NOT NULL,
    TO   DATE          NOT NULL,
);

CREATE TABLE ALGORE_DISH (
    ID        UUID           PRIMARY KEY DEFAULT gen_random_uuid(),
    NAME      VARCHAR2(100)  NOT NULL,
    SOURCE    VARCHAR2(1000) NOT NULL,
    PREP_TIME INTEGER        NOT NULL,
    
);

CREATE TABLE 
